import 'package:flutter/material.dart';

/// Simple localization helper class
class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  /// Get the current locale
  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  /// Supported locales delegate
  static const LocalizationsDelegate<AppLocalizations> delegate = _AppLocalizationsDelegate();

  /// Get localized string
  String get(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? 
           _localizedValues['tr']![key] ?? 
           key;
  }

  /// All localized values
  static final Map<String, Map<String, String>> _localizedValues = {
    'tr': {
      'appTitle': 'DOMINOiT',
      'smartPlantMonitoring': 'Akıllı Bitki İzleme',
      'developedBy': 'Geliştiren',
      'fromTeam': 'Ekal Tech Ekibi',
      'settings': 'Ayarlar',
      'esp32Configuration': 'ESP32 Yapılandırması',
      'esp32BaseUrl': 'ESP32 Temel URL',
      'testConnection': 'Bağlantıyı Test Et',
      'connectionSuccessful': 'Bağlantı başarılı!',
      'connectionFailed': 'Bağlantı başarısız. URL\'yi ve ESP32\'yi kontrol edin.',
      'rgbCalibration': 'RGB Kalibrasyonu',
      'rgbCalibrationDescription': 'Sağlıklı bir bitki için hedef RGB değerlerini ayarlayın.',
      'targetColorPreview': 'Hedef Renk Önizlemesi',
      'appearance': 'Görünüm',
      'darkMode': 'Karanlık Mod',
      'darkModeEnabled': 'Karanlık mod etkin',
      'lightModeEnabled': 'Açık mod etkin',
      'resetToDefaults': 'Varsayılanlara Sıfırla',
      'resetSettings': 'Ayarları Sıfırla',
      'resetSettingsConfirm': 'Tüm ayarları varsayılanlara sıfırlamak istediğinizden emin misiniz?',
      'cancel': 'İptal',
      'reset': 'Sıfırla',
      'settingsSaved': 'Ayarlar başarıyla kaydedildi',
      'settingsReset': 'Ayarlar varsayılanlara sıfırlandı',
      'appInformation': 'Uygulama Bilgileri',
      'version': 'Sürüm',
      'developer': 'Geliştirici',
      'team': 'Ekip',
      'language': 'Dil',
      'selectLanguage': 'Dil Seçin',
      'turkish': 'Türkçe',
      'english': 'English',
      'russian': 'Русский',
      'home': 'Ana Sayfa',
      'liveSensorData': 'Canlı Sensör Verileri',
      'plantStressScore': 'Bitki Stres Skoru',
      'capturePlantPhoto': 'Bitki Fotoğrafı Çek',
      'refreshEspData': 'ESP Verilerini Yenile',
      'simulationMode': 'Simülasyon Modu',
      'simulationModeEnabled': 'Simülasyon modu etkin',
      'esp32Mode': 'ESP32 Modu',
      'esp32ModeEnabled': 'ESP32 modu etkin',
      'connectedToEsp32': 'ESP32\'ye bağlandı',
      'noEsp32Connection': 'ESP32 Bağlantısı yok',
      'noSensorData': 'Sensör verisi yok',
      'pullToRefresh': 'Yenilemek için aşağı çekin veya ESP32 bağlantısını kontrol edin',
      'temperature': 'Sıcaklık',
      'humidity': 'Nem',
      'soilMoisture': 'Toprak Nem',
      'normal': 'Normal',
      'cold': 'Soğuk',
      'hot': 'Sıcak',
      'dry': 'Kuru',
      'humid': 'Nemli',
      'wet': 'Islak',
      'rgbAnalysis': 'RGB Analizi',
      'captureOrSelectImage': 'Bitki görüntüsü çekin veya seçin',
      'camera': 'Kamera',
      'gallery': 'Galeri',
      'analyzePlant': 'Bitkiyi Analiz Et',
      'analyzing': 'Analiz ediliyor...',
      'runSimulation': 'Simülasyon Çalıştır',
      'clear': 'Temizle',
      'analysisResult': 'Analiz Sonucu',
      'stressLevel': 'Stres Seviyesi',
      'rgbComparison': 'RGB Karşılaştırması',
      'captured': 'Yakalanan',
      'target': 'Hedef',
      'healthy': 'Sağlıklı',
      'moderate': 'Orta',
      'stressed': 'Stresli',
      'critical': 'Kritik',
      'plantAppearsHealthy': 'Bitki sağlıklı görünüyor',
      'plantShowsMinorStress': 'Bitki hafif stres belirtisi gösteriyor',
      'plantModeratelyStressed': 'Bitki orta düzeyde stresli',
      'plantRequiresAttention': 'Bitki acil dikkat gerektiriyor',
      'highStressDetected': 'Yüksek stres tespit edildi! Harekete geçin.',
      'notificationWillBeSent': 'Yüksek stres seviyeleri için bildirim gönderilecektir.',
      'targetRgbFromSettings': 'Hedef RGB (Ayarlardan)',
      'noAnalysisYet': 'Henüz analiz yok',
      'capturePhotoToAnalyze': 'Stresi analiz etmek için bitki fotoğrafı çekin',
      'healthLevel': 'Sağlık Seviyesi',
      'somethingWentWrong': 'Bir şeyler ters gitti',
      'pleaseEnterUrl': 'Lütfen ESP32 URL\'sini girin',
      'urlMustStartWithHttp': 'URL http:// veya https:// ile başlamalıdır',
      'rgbValuesMustBeNumbers': 'RGB değerleri sayı olmalıdır',
      'rgbValuesBetween0And255': 'RGB değerleri 0 ile 255 arasında olmalıdır',
      'plantStressDetected': 'Bitki stresi tespit edildi! Hemen kontrol edin.',
    },
    'en': {
      'appTitle': 'DOMINOiT',
      'smartPlantMonitoring': 'Smart Plant Monitoring',
      'developedBy': 'Developed by',
      'fromTeam': 'Ekal Tech Team',
      'settings': 'Settings',
      'esp32Configuration': 'ESP32 Configuration',
      'esp32BaseUrl': 'ESP32 Base URL',
      'testConnection': 'Test Connection',
      'connectionSuccessful': 'Connection successful!',
      'connectionFailed': 'Connection failed. Check URL and ESP32.',
      'rgbCalibration': 'RGB Calibration',
      'rgbCalibrationDescription': 'Set the target RGB values for a healthy plant.',
      'targetColorPreview': 'Target Color Preview',
      'appearance': 'Appearance',
      'darkMode': 'Dark Mode',
      'darkModeEnabled': 'Dark theme enabled',
      'lightModeEnabled': 'Light theme enabled',
      'resetToDefaults': 'Reset to Defaults',
      'resetSettings': 'Reset Settings',
      'resetSettingsConfirm': 'Are you sure you want to reset all settings to defaults?',
      'cancel': 'Cancel',
      'reset': 'Reset',
      'settingsSaved': 'Settings saved successfully',
      'settingsReset': 'Settings reset to defaults',
      'appInformation': 'App Information',
      'version': 'Version',
      'developer': 'Developer',
      'team': 'Team',
      'language': 'Language',
      'selectLanguage': 'Select Language',
      'turkish': 'Türkçe',
      'english': 'English',
      'russian': 'Русский',
      'home': 'Home',
      'liveSensorData': 'Live Sensor Data',
      'plantStressScore': 'Plant Stress Score',
      'capturePlantPhoto': 'Capture Plant Photo',
      'refreshEspData': 'Refresh ESP Data',
      'simulationMode': 'Simulation Mode',
      'simulationModeEnabled': 'Simulation mode enabled',
      'esp32Mode': 'ESP32 Mode',
      'esp32ModeEnabled': 'ESP32 mode enabled',
      'connectedToEsp32': 'Connected to ESP32',
      'noEsp32Connection': 'No ESP32 Connection',
      'noSensorData': 'No sensor data available',
      'pullToRefresh': 'Pull down to refresh or check ESP32 connection',
      'temperature': 'Temperature',
      'humidity': 'Humidity',
      'soilMoisture': 'Soil Moisture',
      'normal': 'Normal',
      'cold': 'Cold',
      'hot': 'Hot',
      'dry': 'Dry',
      'humid': 'Humid',
      'wet': 'Wet',
      'rgbAnalysis': 'RGB Analysis',
      'captureOrSelectImage': 'Capture or select a plant image',
      'camera': 'Camera',
      'gallery': 'Gallery',
      'analyzePlant': 'Analyze Plant',
      'analyzing': 'Analyzing...',
      'runSimulation': 'Run Simulation',
      'clear': 'Clear',
      'analysisResult': 'Analysis Result',
      'stressLevel': 'Stress Level',
      'rgbComparison': 'RGB Comparison',
      'captured': 'Captured',
      'target': 'Target',
      'healthy': 'Healthy',
      'moderate': 'Moderate',
      'stressed': 'Stressed',
      'critical': 'Critical',
      'plantAppearsHealthy': 'Plant appears healthy',
      'plantShowsMinorStress': 'Plant shows minor stress',
      'plantModeratelyStressed': 'Plant is moderately stressed',
      'plantRequiresAttention': 'Plant requires immediate attention',
      'highStressDetected': 'High stress detected! Take action.',
      'notificationWillBeSent': 'Notification will be sent for high stress levels.',
      'targetRgbFromSettings': 'Target RGB (from Settings)',
      'noAnalysisYet': 'No analysis yet',
      'capturePhotoToAnalyze': 'Capture a plant photo to analyze stress',
      'healthLevel': 'Health Level',
      'somethingWentWrong': 'Something went wrong',
      'pleaseEnterUrl': 'Please enter ESP32 URL',
      'urlMustStartWithHttp': 'URL must start with http:// or https://',
      'rgbValuesMustBeNumbers': 'RGB values must be numbers',
      'rgbValuesBetween0And255': 'RGB values must be between 0 and 255',
      'plantStressDetected': 'Plant stress detected! Check immediately.',
    },
    'ru': {
      'appTitle': 'DOMINOiT',
      'smartPlantMonitoring': 'Умный мониторинг растений',
      'developedBy': 'Разработал',
      'fromTeam': 'командой Ekal Tech',
      'settings': 'Настройки',
      'esp32Configuration': 'Конфигурация ESP32',
      'esp32BaseUrl': 'Базовый URL ESP32',
      'testConnection': 'Проверить соединение',
      'connectionSuccessful': 'Соединение успешно!',
      'connectionFailed': 'Ошибка соединения. Проверьте URL и ESP32.',
      'rgbCalibration': 'Калибровка RGB',
      'rgbCalibrationDescription': 'Установите целевые значения RGB для здорового растения.',
      'targetColorPreview': 'Предпросмотр целевого цвета',
      'appearance': 'Внешний вид',
      'darkMode': 'Тёмный режим',
      'darkModeEnabled': 'Тёмная тема включена',
      'lightModeEnabled': 'Светлая тема включена',
      'resetToDefaults': 'Сбросить настройки',
      'resetSettings': 'Сбросить настройки',
      'resetSettingsConfirm': 'Вы уверены, что хотите сбросить все настройки?',
      'cancel': 'Отмена',
      'reset': 'Сбросить',
      'settingsSaved': 'Настройки сохранены',
      'settingsReset': 'Настройки сброшены',
      'appInformation': 'Информация о приложении',
      'version': 'Версия',
      'developer': 'Разработчик',
      'team': 'Команда',
      'language': 'Язык',
      'selectLanguage': 'Выберите язык',
      'turkish': 'Türkçe',
      'english': 'English',
      'russian': 'Русский',
      'home': 'Главная',
      'liveSensorData': 'Данные датчиков',
      'plantStressScore': 'Оценка стресса растения',
      'capturePlantPhoto': 'Сделать фото растения',
      'refreshEspData': 'Обновить данные ESP',
      'simulationMode': 'Режим симуляции',
      'simulationModeEnabled': 'Режим симуляции включён',
      'esp32Mode': 'Режим ESP32',
      'esp32ModeEnabled': 'Режим ESP32 включён',
      'connectedToEsp32': 'Подключено к ESP32',
      'noEsp32Connection': 'Нет подключения к ESP32',
      'noSensorData': 'Нет данных датчиков',
      'pullToRefresh': 'Потяните для обновления или проверьте подключение к ESP32',
      'temperature': 'Температура',
      'humidity': 'Влажность',
      'soilMoisture': 'Влажность почвы',
      'normal': 'Нормально',
      'cold': 'Холодно',
      'hot': 'Жарко',
      'dry': 'Сухо',
      'humid': 'Влажно',
      'wet': 'Мокро',
      'rgbAnalysis': 'RGB анализ',
      'captureOrSelectImage': 'Сделайте или выберите фото растения',
      'camera': 'Камера',
      'gallery': 'Галерея',
      'analyzePlant': 'Анализировать растение',
      'analyzing': 'Анализ...',
      'runSimulation': 'Запустить симуляцию',
      'clear': 'Очистить',
      'analysisResult': 'Результат анализа',
      'stressLevel': 'Уровень стресса',
      'rgbComparison': 'Сравнение RGB',
      'captured': 'Захвачено',
      'target': 'Цель',
      'healthy': 'Здоровое',
      'moderate': 'Умеренный',
      'stressed': 'Под стрессом',
      'critical': 'Критический',
      'plantAppearsHealthy': 'Растение выглядит здоровым',
      'plantShowsMinorStress': 'Растение показывает лёгкий стресс',
      'plantModeratelyStressed': 'Растение умеренно под стрессом',
      'plantRequiresAttention': 'Растению требуется немедленное внимание',
      'highStressDetected': 'Обнаружен высокий стресс! Примите меры.',
      'notificationWillBeSent': 'Уведомление будет отправлено при высоком уровне стресса.',
      'targetRgbFromSettings': 'Целевой RGB (из настроек)',
      'noAnalysisYet': 'Пока нет анализа',
      'capturePhotoToAnalyze': 'Сделайте фото растения для анализа стресса',
      'healthLevel': 'Уровень здоровья',
      'somethingWentWrong': 'Что-то пошло не так',
      'pleaseEnterUrl': 'Пожалуйста, введите URL ESP32',
      'urlMustStartWithHttp': 'URL должен начинаться с http:// или https://',
      'rgbValuesMustBeNumbers': 'Значения RGB должны быть числами',
      'rgbValuesBetween0And255': 'Значения RGB должны быть от 0 до 255',
      'plantStressDetected': 'Обнаружен стресс растения! Проверьте немедленно.',
    },
  };
}

/// Delegate for AppLocalizations
class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['tr', 'en', 'ru'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
